# Generated by Django 4.2.5 on 2023-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_watcher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='line',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='line',
            name='icon',
            field=models.URLField(),
        ),
    ]
