# Generated by Django 4.2.5 on 2023-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_line_line_number_rename_name_line_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirun',
            name='error',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
